services:
  reverse-proxy:
    image: traefik:latest
    networks:
      - proxy
    command:
      - "--log.level=DEBUG"
      - "--log.filePath=/usr/traefik.log"
      - "--api=true"
      - "--api.dashboard=true"
      
      - "--providers.docker.network=proxy"
      - "--providers.docker.exposedByDefault=false"
      - "--entryPoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entryPoints.web.http.redirections.entrypoint.scheme=https"
      
      - "--entryPoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      
      - --certificatesresolvers.myresolver.acme.email=quentin.beaufort@ynov.com
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/etc/letsencrypt/:/letsencrypt"
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`airlux.m1-iot.ynov.cloud`) && PathPrefix(`/dashboard`)
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certresolver=myresolver
      - traefik.http.routers.traefik.service=api@internal
networks:
  proxy:
    name: proxy
    external: true
volumes:
  letsencrypt:
    name: letsencrypt
